veggies = [
    "Asparagus",
    "Avocado",
    "BBQ vegies",
    "Bean",
    "Beetroot",
    "Potato salad",
    "Pak choy",
    "Broccoli",
    "Brussels sprouts",
    "Butternut pumpkin in orange",
    "Cabbage",
    "Carrot",
    "Cauliflower",
    "Cauliflower and broccoli gratin",
    "Celeriac",
    "Celery",
    "Chickpea and couscous salad",
    "Citrus coleslaw",
    "Corn" ,
    "Sweet corn",
    "Crunchy Waldorf salad",
    "Cucumber",
    "Eggplant",
    "Aubergine",
    "Eggplant dip",
    "Fennel",
    "Salad",
    "Guacamole",
    "Honeyed greens",
    "Pasta salad",
    "Lettuce",
    "Corn and tomato salad",
    "Mushroom",
    "Mustard and honey corn on the cob",
    "Onion",
    "Pea",
    "Potato",
    "Potato caesar salad",
    "Pumpkin",
    "Radish",
    "Ratatouille",
    "Salsa",
    "Sesame brussels sprouts",
    "Spinach",
    "Squash",
    "Sweet potato",
    "Thai noodle salad",
    "Tomato",
    "Tomato and garlic bruschetta",
    "Turnip",
    "Vegetable stock",
    "Vegie curry",
    "Vegie lentil soup",
    "Walnut lentil salad",
    "Warm roasted vegetable salad",
    "courgette"]